# Generated by Django 4.0.1 on 2022-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_password_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='logo',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
