# Generated by Django 4.0.1 on 2022-01-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_password_logo_alter_password_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'ordering': ['-id']},
        ),
    ]
