# Generated by Django 4.0.1 on 2022-01-17 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_password_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='authorized',
            field=models.ManyToManyField(related_name='coowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
