# Generated by Django 4.0.1 on 2022-01-17 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_password_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='last_change',
            field=models.DateField(default=datetime.datetime(2022, 1, 17, 14, 9, 4, 624731, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
