# Generated by Django 4.0.1 on 2022-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_password_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='last_change',
            field=models.DateTimeField(),
        ),
    ]
