# Generated by Django 4.0.1 on 2022-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_password_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
