# Generated by Django 4.0.1 on 2022-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_password_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='grade',
            field=models.FloatField(),
        ),
    ]
